use_frameworks!

target 'PatrickMultipleSelectionTableview_Example' do
  pod 'PatrickMultipleSelectionTableview', :path => 'https://github.com/pratikpanchal13/PatrickMultipleSelectionTableview.git'

  target 'PatrickMultipleSelectionTableview_Tests' do
    inherit! :search_paths

    
  end
end
